### ISSUE TITLE
Rename "RDF*" to something else

### ISSUE THREAD

**Issue by akuckartz** [w3c/EasierRDF#76]
The name "RDF*" has the negative property that it is not just a string, but also a regular expression. Some search engines make it difficult or impossible to search for "RDF*" without interpreting the name as a regular expression.

Some suggestions:
* RDF star
* RDFx

**Comment by hartig** [comment]
I don't think it is a good idea to rename RDF* at this point. However, I understand the issue related to search engines. A possible way to address this issue is to include keywords such as "RDF star", "RDFstar", "SPARQL star", etc, in the metadata sections of the documents about the approach; this way, search engine can pick up these keywords and, then, searches for these keywords will end up showing the right hits.

**Comment by hartig** [comment]
By the way, as you may have noticed already, we have a separate repo for the RDF*/SPARQL* spec now: https://github.com/w3c/rdf-star/

**Comment by akuckartz** [comment]
Closing this as I have opened a corresponding issue in the RDF star /SPARQL star repository.
